/* 
Andre Little
Class: MiU
Term: 1311
Completed Date: 10/31/2013
Project 1: Gaming Vault - JSON 
*/

var json = {
	"videoGame1": {
		"platform": ["Platform:", "3DS"],
		"name1": ["Title:", "Pokemon X"],
		"genre": ["Genre:", "RPG (Role Playing Game)"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "E (Everyone)"],
		"condition": ["Games Condition:", "100"],
		"date": ["Release Date:", "2013-10-12"],
		"addInfo": ["Additional Info:", ""],
	},
	"videoGame2": {
		"platform": ["Platform:", "3DS"],
		"name1": ["Title:", "Pokemon Y"],
		"genre": ["Genre:", "RPG (Role Playing Game)"],
		"region": ["Region:", "PAL"],
		"ratings": ["ESRB Rating:", "E (Everyone)"],
		"condition": ["Games Condition:", "100"],
		"date": ["Release Date:", "2013-10-12"],
		"addInfo": ["Additional Info:", "This version has better Pokemon"],

	},
	"videoGame3": {
		"platform": ["Platform:", "Wii U"],
		"name1": ["Title:", "Call of Duty: Black Ops II"],
		"genre": ["Genre:", "FPS (First Person Shooter) / Shooter"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "M (Mature 17+)"],
		"condition": ["Games Condition:", "100"],
		"date": ["Release Date:", "2012-11-11"],
		"addInfo": ["Additional Info:", ""],
	},
	"videoGame4": {
		"platform": ["Platform:", "PlayStation 3"],
		"name1": ["Title:", "Call of Duty: Black Ops II"],
		"genre": ["Genre:", "FPS (First Person Shooter) / Shooter"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "M (Mature 17+)"],
		"condition": ["Games Condition:", "100"],
		"date": ["Release Date:", "2012-11-11"],
		"addInfo": ["Additional Info:", ""],
	},
	"videoGame5": {
		"platform": ["Platform:", "PlayStation 3"],
		"name1": ["Title:", "BattleField 4"],
		"genre": ["Genre:", "FPS (First Person Shooter) / Shooter"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "M (Mature 17+)"],
		"condition": ["Games Condition:", "100"],
		"date": ["Release Date:", "2013-10-30"],
		"addInfo": ["Additional Info:", ""],
	},
	"videoGame6": {
		"platform": ["Platform:", "PlayStation 3"],
		"name1": ["Title:", "Assassin's Creed 4"],
		"genre": ["Genre:", "Action / Adventure"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "M (Mature 17+)"],
		"condition": ["Games Condition:", "50"],
		"date": ["Release Date:", "2013-10-10"],
		"addInfo": ["Additional Info:", ""],
	},
	"videoGame7": {
		"platform": ["Platform:", "PlayStation 3"],
		"name1": ["Title:", "God of War Series Collection"],
		"genre": ["Genre:", "Action / Adventure"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "AO (Adults Only)"],
		"condition": ["Games Condition:", "100"],
		"date": ["Release Date:", "2011-03-02"],
		"addInfo": ["Additional Info:", "Great Games"],
	},
	"videoGame8": {
		"platform": ["Platform:", "XBox 360"],
		"name1": ["Title:", "Halo 4"],
		"genre": ["Genre:", "FPS (First Person Shooter) / Shooter"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "M (Mature 17+)"],
		"condition": ["Games Condition:", "100"],
		"date": ["Release Date:", "2012-08-22"],
		"addInfo": ["Additional Info:", ""],
	},
	"videoGame9": {
		"platform": ["Platform:", "XBox 360"],
		"name1": ["Title:", "Gears Of War"],
		"genre": ["Genre:", "FPS (First Person Shooter) / Shooter"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "M (Mature 17+)"],
		"condition": ["Games Condition:", "25"],
		"date": ["Release Date:", "2001-1-1"],
		"addInfo": ["Additional Info:", ""],
	},
	"videoGame10": {
		"platform": ["Platform:", "3DS"],
		"name1": ["Title:", "Mario and Luigi: Dream Team"],
		"genre": ["Genre:", "RPG (Role Playing Game)"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "E10+ (Everyone 10+)"],
		"condition": ["Games Condition:", "50"],
		"date": ["Release Date:", "2013-08-13"],
		"addInfo": ["Additional Info:", ""],
	},
	"videoGame11": {
		"platform": ["Platform:", "Wii U"],
		"name1": ["Title:", "Splinter Cell"],
		"genre": ["Genre:", "Action / Adventure"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "M+ (Mature 17+)"],
		"condition": ["Games Condition:", "25"],
		"date": ["Release Date:", "2013-08-22"],
		"addInfo": ["Additional Info:", ""],
	},
	"videoGame12": {
		"platform": ["Platform:", "3DS"],
		"name1": ["Title:", "Mario and Luigi: Dream Team"],
		"genre": ["Genre:", "RPG (Role Playing Game)"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "E10+ (Everyone 10+)"],
		"condition": ["Games Condition:", "50"],
		"date": ["Release Date:", "2013-08-13"],
		"addInfo": ["Additional Info:", ""],
	},
	"videoGame13": {
		"platform": ["Platform:", "3DS"],
		"name1": ["Title:", "Mario and Luigi: Dream Team"],
		"genre": ["Genre:", "RPG (Role Playing Game)"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "E10+ (Everyone 10+)"],
		"condition": ["Games Condition:", "50"],
		"date": ["Release Date:", "2013-08-13"],
		"addInfo": ["Additional Info:", ""],
	},
		"platform": ["Platform:", "3DS"],
		"name1": ["Title:", "Mario and Luigi: Dream Team"],
		"genre": ["Genre:", "RPG (Role Playing Game)"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "E10+ (Everyone 10+)"],
		"condition": ["Games Condition:", "50"],
		"date": ["Release Date:", "2013-08-13"],
		"addInfo": ["Additional Info:", ""],
	},
		"platform": ["Platform:", "3DS"],
		"name1": ["Title:", "Yugioh"],
		"genre": ["Genre:", "RPG (Role Playing Game)"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "E10+ (Everyone 10+)"],
		"condition": ["Games Condition:", "100"],
		"date": ["Release Date:", "2014-04-14"],
		"addInfo": ["Additional Info:", ""],
	},
		"platform": ["Platform:", "3DS"],
		"name1": ["Title:", "Sticker Stars"],
		"genre": ["Genre:", "RPG (Role Playing Game)"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "E (Everone)"],
		"condition": ["Games Condition:", "50"],
		"date": ["Release Date:", "2013-04-13"],
		"addInfo": ["Additional Info:", ""],
	},
	"videoGame17": {
		"platform": ["Platform:", "3DS"],
		"name1": ["Title:", "Barbie"],
		"genre": ["Genre:", "Puzzle"],
		"region": ["Region:", "PAL"],
		"ratings": ["ESRB Rating:", "E (Everyone)"],
		"condition": ["Games Condition:", "50"],
		"date": ["Release Date:", "2009-08-13"],
		"addInfo": ["Additional Info:", ""],
	},
	"videoGame18": {
		"platform": ["Platform:", "PlayStation 3"],
		"name1": ["Title:", "GTA 5"],
		"genre": ["Genre:", "MMO (Massive Multiplayer Online)"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "AO (Adults Only)"],
		"condition": ["Games Condition:", "100"],
		"date": ["Release Date:", "2013-09-17"],
		"addInfo": ["Additional Info:", ""],
	},	
	"videoGame19": {
		"platform": ["Platform:", "Wii U"],
		"name1": ["Title:", "Call Of Duty:Ghost"],
		"genre": ["Genre:", "FPS (First Person Shooter) / Shooter)"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "M (Mature 17+)"],
		"condition": ["Games Condition:", "100"],
		"date": ["Release Date:", "2013-11-05"],
		"addInfo": ["Additional Info:", ""],
	},
	"videoGame20": {
		"platform": ["Platform:", "3DS"],
		"name1": ["Title:", "Conquest"],
		"genre": ["Genre:", "RPG (Role Playing Game)"],
		"region": ["Region:", "NTSC"],
		"ratings": ["ESRB Rating:", "E10+ (Everyone 10+)"],
		"condition": ["Games Condition:", "75"],
		"date": ["Release Date:", "2003-08-13"],
		"addInfo": ["Additional Info:", ""],
	}
}


